### ISSUE TITLE
根目录下的key.json能不能开放出来

### ISSUE THREAD

**Issue by messikiller** [museui/muse-docs#3]
公司没有外网，想把doc下载下来在本地npm run build，结果一直报错缺少 key.json 这个文件

**Comment by myronliu347** [comment]
不可以哦，key.json涉及到私人账号信息

**Comment by mapletower** [comment]
> 公司没有外网，想把doc下载下来在本地npm run build，结果一直报错缺少 key.json 这个文件

简单跑起来的话，把`i18n.js`里面的config拷一个出来新建`key.json`就可以了。
